<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Xss;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uceap_tfa_form_tfa_setup_alter(&$form, FormStateInterface $form_state, $form_id) {
  $plugin_settings = \Drupal::config('tfa.settings')->get('login_plugin_settings');
  $settings = $plugin_settings['uceap_tfa_trusted_browser'] ?? [];
  if ($form_state->get('step_method') == "tfa_totp") {
    $form['apps'] = [
      '#type' => 'html_tag',
      '#tag' => 'h2',
      '#value' => 'Setup MFA using your mobile device or other app',
    ];
    $form['info'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $settings['instructions_markup'] ?? 'Instructions missing',
      '#allowed_tags' => array_merge(Xss::getAdminTagList(), ['script']),
    ];
  }
}
